# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('group_type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('HIDDEN', 'Hidden')], max_length=10)),
                ('profile_img', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(max_length=120)),
            ],
        ),
    ]
