# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20170726_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygroup',
            name='group_type',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('HIDDEN', 'Hidden')], default='PUBLIC', max_length=10),
        ),
    ]
