# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 06:04
from __future__ import unicode_literals

from django.db import migrations
import utils.fields.custom_imagefiled


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20170726_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygroup',
            name='profile_img',
            field=utils.fields.custom_imagefiled.CustomImageField(blank=True, default='', upload_to='group'),
            preserve_default=False,
        ),
    ]
