# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0004_auto_20170728_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygroup',
            name='members',
        ),
        migrations.AddField(
            model_name='mygroup',
            name='member',
            field=models.ManyToManyField(related_name='groups_joined', through='group.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mygroup',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
