# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20170730_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='num_of_members',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
