# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_mygroup_num_of_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptag',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='mygroup',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
