# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20170801_1438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mygroup',
            name='member',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
