# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20170803_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygroup',
            name='num_of_members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
