# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=12, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='계정을 삭제하지 않고 비활성화 시킬때 체크를 해제하십시오.', verbose_name='계정 활성화'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Admin page에 접속할 수 있는 권한을 부여합니다.', verbose_name='스태프 권한'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=16, unique=True, verbose_name='닉네임'),
        ),
    ]
