# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 06:04
from __future__ import unicode_literals

from django.db import migrations
import utils.fields.custom_imagefiled


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_img',
            field=utils.fields.custom_imagefiled.CustomImageField(blank=True, upload_to='member'),
        ),
    ]
