# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_myuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='relations',
            field=models.ManyToManyField(through='member.UserRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
