# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20170803_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-pk'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
